# Generated by Django 4.2.5 on 2023-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default=False, max_length=500)),
                ('PRN', models.CharField(default=True, max_length=200)),
                ('name', models.CharField(default=False, max_length=255)),
                ('TcNo', models.IntegerField(default=False)),
                ('date', models.DateField(default=False)),
                ('reason', models.TextField(default=False)),
                ('mobile', models.IntegerField(default=False)),
            ],
        ),
    ]
