# Generated by Django 4.2.5 on 2023-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='TcNo',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='college_name',
            field=models.CharField(default=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='date',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='mobile',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='reason',
            field=models.TextField(default=True),
        ),
    ]
