# Generated by Django 4.2.5 on 2023-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapapp', '0002_alter_scrapeddata_tcno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='date',
            field=models.IntegerField(default=True),
        ),
    ]
