# Generated by Django 4.2.5 on 2023-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapapp', '0003_alter_scrapeddata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
