# Generated by Django 4.2.5 on 2023-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapapp', '0006_alter_scrapeddata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='mobile',
            field=models.IntegerField(default=True, max_length=10),
        ),
    ]
